gems:
  - bourbon
  - neat
  - jekyll-sitemap

# Structure configuration
source: source
destination: build

assets:
  dirname: assets
  baseurl: /assets/
  cachebust: soft
  source:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets

# Site settings
title: Myles.RED
description: Some random-ass playlists made by Myles Braithwaite.
permalink: /:year-:month-:day/:title.html

# Author information
email: me@myles.red
twitter_username: mylesb

# URL settings
baseurl: ""
url: "http://myles.red"

# Build settings
markdown: kramdown
